server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/demo_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 0102linh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect